[package]
name = "jacdac-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
circular-buffer = { version = "0.1.9", default-features = false }
crc16 = "0.4.0"
downcast-rs = { version = "1.2.1", default-features = false }
